name: Build and Package

on:
  push:
    branches:
      - "main"

jobs:
  Build_Release:
    name: Create Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Ruby Environment"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.5"
      - name: "Prepare FPM"
        run: gem install fpm

      - name: Prepare the package
        run: |
          export VERSION=`head -n 1 VERSION`
          mkdir -p pkg/usr/bin
          sed -n '/### Unit tests below here/q;p' linux/monchero-agent.py |sed 's/^VERSION=.*$/VERSION='${VERSION}'/' > pkg/usr/bin/monchero-agent
          sed -n '/### Unit tests below here/q;p' linux/mstatus.py |sed 's/^VERSION=.*$/VERSION='${VERSION}'/' > pkg/usr/bin/mstatus
          chmod 755 pkg/usr/bin/*

      - name: Make packages
        run: |
          export VERSION=`head -n 1 VERSION`
          fpm -s dir -t rpm -p monchero-agent-${VERSION}-${{ github.run_id }}.rpm -v 1.0 --iteration ${{ github.run_id }}  -n monchero-agent -m devops -C pkg .
          fpm -s dir -t deb -p monchero-agent-${VERSION}-${{ github.run_id }}.deb -v 1.0 --iteration ${{ github.run_id }}  -n monchero-agent -m devops -C pkg .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            monchero-agent-*.deb
            monchero-agent-*.rpm
