name: Build and Package

on: push

jobs:
  Build_Release:
    name: Create Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Ruby Environment"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.5"
      - name: "Prepare FPM"
        run: gem install fpm

      - name: Prepare the package
        run: |
          export VERSION="${{ github.ref_name }}"
          mkdir -p pkg/usr/bin
          sed -n '/### Unit tests below here/q;p' linux/monchero-agent.py |sed 's/^VERSION=.*$/VERSION="'${VERSION}'"/' > pkg/usr/bin/monchero-agent
          sed -n '/### Unit tests below here/q;p' linux/mstatus.py |sed 's/^VERSION=.*$/VERSION="'${VERSION}'"/' > pkg/usr/bin/mstatus
          chmod 755 pkg/usr/bin/*

      - name: Make packages
        run: |
          fpm -s dir -t rpm -p monchero-agent-"${{ github.ref_name }}"-${{ github.run_id }}.rpm -v "${{ github.ref_name }}" --iteration ${{ github.run_id }}  -n monchero-agent -m devops -C pkg .
          fpm -s dir -t deb -p monchero-agent-"${{ github.ref_name }}"-${{ github.run_id }}.deb -v "${{ github.ref_name }}" --iteration ${{ github.run_id }}  -n monchero-agent -m devops -C pkg .

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            monchero-agent-*.deb
            monchero-agent-*.rpm
          tag_name: "${{ github.ref_name }}"
